# Generated by Django 3.0.3 on 2020-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('TD', 'to-do'), ('IP', 'in-process'), ('D', 'done')], max_length=2)),
            ],
        ),
    ]
